name: Rodar script diário

on:
  schedule:
    - cron: '0 9 * * *' # roda todo dia às 9h UTC (6h no Brasil)
  workflow_dispatch: # permite rodar manualmente

jobs:
  run:
    runs-on: ubuntu-latest

    env: # 🔐 variáveis de ambiente seguras
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Executar script
        run: |
          python main.py
